target 'iosApp' do
  use_frameworks! :linkage => :static # melhora compatibilidade
  use_modular_headers! # ajuda a importar módulos internos corretamente
  
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  
  pod 'FirebaseRemoteConfig'
  pod 'FirebaseAnalytics'
end